// FORCE UPDATE ACTION TYPES
export const GET_APP_VERSION_FETCH = "GET_APP_VERSION_FETCH";
export const GET_APP_VERSION_SUCCESS = "GET_APP_VERSION_SUCCESS";
export const GET_APP_VERSION_FAILED = "GET_APP_VERSION_FAILED";